# INSERINDO A IMAGEM DO NODE NO NOSSO CONTAINER
FROM node

# DEFININDO DIRETORIO ONDE AS INFORMACOES SOBRE O CONTAINER FIQUEM CONTIDAS
WORKDIR /usr/app

# COPIANDO O ARQUIVO PACKAGE.JSON PARA O WORKDIR
COPY package.json ./

# EXECUTANTO O COMANDO PARA INSTALAÇÃO E INICIAÇÃO DO NOSSO PROJETO
RUN npm install

# COPIANDO TUDO PARA O CONTAINER (SALVO OS ITENS LISTADOS NO .DOCKERINGORE)
COPY . .

# LIBERANDO A PORTA QUE UTILIZAMOS NO CONTAINER
EXPOSE 3000

# PERMITINDO OS COMANDOS DE SCRIPTS
CMD ["npm", "run", "start:dev"]